import React, { useEffect, useState } from 'react';
import chetanHeroImg from '../assets/images/chetan_profile_hero_1782383152595.jpg';

type Message = { _id: string; name: string; email: string; subject: string; message: string; status: 'new' | 'read' | 'archived'; createdAt: string };
type Content = Record<string, any>;
type Page = 'dashboard' | 'profile' | 'about' | 'education' | 'skills' | 'projects' | 'experience' | 'certifications' | 'achievements' | 'resume' | 'social' | 'githubSettings' | 'messages' | 'settings';
const navigation: [Page, string][] = [['dashboard', 'Dashboard'], ['profile', 'Profile / Hero'], ['about', 'About'], ['education', 'Education'], ['skills', 'Skills'], ['projects', 'Projects'], ['experience', 'Experience / Internships'], ['certifications', 'Certificates'], ['achievements', 'Achievements'], ['resume', 'Resume'], ['social', 'Social Links & Contact'], ['githubSettings', 'GitHub Settings'], ['messages', 'Messages'], ['settings', 'Settings']];

const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL ||
  'http://localhost:5000/api';

async function request(
  path: string,
  options: RequestInit = {}
) {
  const apiUrl = `${API_BASE_URL.replace(/\/$/, '')}${path}`;

  const response = await fetch(apiUrl, {
    credentials: 'include',

    headers: {
      ...(options.body instanceof FormData
        ? {}
        : {
            'Content-Type': 'application/json',
          }),
      ...options.headers,
    },

    ...options,
  });

  const data = await response.json().catch(() => ({}));

  if (!response.ok) {
    throw new Error(
      data.error || 'Request failed.'
    );
  }

  return data;
}

const Shell: React.FC<React.PropsWithChildren> = ({ children }) => <main className="min-h-screen bg-slate-950 text-slate-100">{children}</main>;
const Field: React.FC<{ label: string; value?: string | number; type?: string; onChange: (value: string) => void; placeholder?: string }> = ({ label, value = '', type = 'text', onChange, placeholder }) => <label className="block text-sm font-medium text-slate-300">{label}<input type={type} value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500" /></label>;
const Area: React.FC<{ label: string; value?: string; onChange: (value: string) => void; rows?: number }> = ({ label, value = '', onChange, rows = 4 }) => <label className="block text-sm font-medium text-slate-300">{label}<textarea value={value} rows={rows} onChange={(e) => onChange(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500" /></label>;
const Toggle: React.FC<{ label: string; checked: boolean; onChange: (value: boolean) => void }> = ({ label, checked, onChange }) => <label className="flex cursor-pointer items-center gap-3 text-sm text-slate-300"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="h-4 w-4 accent-blue-500" />{label}</label>;
const Button: React.FC<React.PropsWithChildren<{ onClick?: () => void; kind?: 'primary' | 'quiet' | 'danger'; type?: 'button' | 'submit'; disabled?: boolean }>> = ({ children, onClick, kind = 'quiet', type = 'button', disabled }) => <button type={type} disabled={disabled} onClick={onClick} className={`rounded-lg px-4 py-2 text-sm font-semibold transition ${kind === 'primary' ? 'bg-blue-600 text-white hover:bg-blue-500' : kind === 'danger' ? 'border border-red-500/50 text-red-300 hover:bg-red-500/10' : 'border border-slate-700 text-slate-200 hover:bg-slate-800'} disabled:opacity-50`}>{children}</button>;
const Card: React.FC<React.PropsWithChildren<{ title: string; description?: string }>> = ({ title, description, children }) => <section className="rounded-xl border border-slate-800 bg-slate-900/60 p-5 shadow-xl shadow-black/10"><h2 className="text-lg font-bold">{title}</h2>{description && <p className="mt-1 text-sm text-slate-400">{description}</p>}<div className="mt-5">{children}</div></section>;

const Upload: React.FC<{ kind: string; accept: string; onUploaded: (url: string) => void; label: string }> = ({ kind, accept, onUploaded, label }) => {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const choose = async (file?: File) => { if (!file) return; setBusy(true); setError(''); try { const form = new FormData(); form.append('file', file); form.append('kind', kind); const result = await request('/api/admin/upload', { method: 'POST', body: form }); onUploaded(result.url); } catch (e) { setError(e instanceof Error ? e.message : 'Upload failed.'); } finally { setBusy(false); } };
  return <div><label className="inline-flex cursor-pointer items-center rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-200 hover:bg-slate-800"><input className="sr-only" type="file" accept={accept} onChange={(e) => choose(e.target.files?.[0])} />{busy ? 'Uploading…' : label}</label>{error && <p className="mt-2 text-xs text-red-300">{error}</p>}</div>;
};

export const AdminApp: React.FC = () => {
  const loginRoute = window.location.pathname === '/admin/login';
  const [page, setPage] = useState<Page>('dashboard'); const [content, setContent] = useState<Content | null>(null); const [checking, setChecking] = useState(!loginRoute); const [notice, setNotice] = useState(''); const [messages, setMessages] = useState<Message[]>([]);
  const load = async () => { const data = await request('/api/admin/content'); setContent(data); return data; };
  useEffect(() => { if (loginRoute) return; request('/api/admin/session').then(load).catch(() => window.location.assign('/admin/login')).finally(() => setChecking(false)); }, [loginRoute]);
  useEffect(() => { if (page === 'messages' || page === 'dashboard') request('/api/admin/messages').then(setMessages).catch((e) => setNotice(e.message)); }, [page]);
  if (loginRoute) return <Login onSuccess={() => window.location.assign('/admin')} />;
  if (checking) return <Shell><p className="p-10 font-mono text-slate-400">Checking private session…</p></Shell>;
  if (!content) return null;
  const setSection = (section: string, value: any) => setContent((current) => current ? { ...current, [section]: value } : current);
  const save = async (section: string) => { try { await request(`/api/admin/content/${section}`, { method: 'PUT', body: JSON.stringify({ value: content[section] }) }); if (section === 'social') await request('/api/admin/content/profile', { method: 'PUT', body: JSON.stringify({ value: content.profile }) }); setNotice('Changes saved. The public portfolio will use the updated data.'); } catch (e) { setNotice(e instanceof Error ? e.message : 'Save failed.'); } };
  const discard = async () => { try { await load(); setNotice('Unsaved changes discarded.'); } catch { setNotice('Unable to reload changes.'); } };
  const logout = async () => { await request('/api/admin/logout', { method: 'POST' }); window.location.assign('/admin/login'); };
  const updateMessage = async (id: string, status: Message['status']) => { const updated = await request(`/api/admin/messages/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); setMessages((all) => all.map((message) => message._id === id ? updated : message)); };
  const saveForPage: Record<Page, string | undefined> = { dashboard: undefined, profile: 'profile', about: 'profile', education: 'education', skills: 'skills', projects: 'projects', experience: 'experience', certifications: 'certifications', achievements: 'achievements', resume: 'resume', social: 'social', githubSettings: 'githubSettings', messages: undefined, settings: undefined };

  return <Shell><div className="flex min-h-screen"><aside className="hidden w-64 shrink-0 border-r border-slate-800 bg-slate-900/70 p-5 lg:block"><a href="/admin" className="mb-8 block"><span className="font-mono text-xs text-blue-400">PRIVATE CMS</span><h1 className="text-xl font-bold">Portfolio Admin</h1></a><nav className="space-y-1">{navigation.map(([key, label]) => <button key={key} onClick={() => setPage(key)} className={`w-full rounded-lg px-3 py-2.5 text-left text-sm ${page === key ? 'bg-blue-600 text-white' : 'text-slate-300 hover:bg-slate-800'}`}>{label}</button>)}</nav></aside><div className="min-w-0 flex-1"><header className="flex items-center justify-between border-b border-slate-800 bg-slate-950/80 px-5 py-4 sm:px-8"><div className="lg:hidden"><select value={page} onChange={(e) => setPage(e.target.value as Page)} className="rounded border border-slate-700 bg-slate-900 px-2 py-1.5 text-sm">{navigation.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><p className="hidden text-sm text-slate-400 lg:block">Manage your portfolio content</p><div className="flex gap-2"><a href="/" className="rounded-lg border border-slate-700 px-3 py-2 text-sm hover:bg-slate-800">View site</a><Button onClick={logout}>Log out</Button></div></header><div className="mx-auto max-w-6xl p-5 sm:p-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs text-blue-400">CMS / {navigation.find(([key]) => key === page)?.[1]}</p><h1 className="mt-1 text-2xl font-bold">{navigation.find(([key]) => key === page)?.[1]}</h1></div>{saveForPage[page] && <div className="flex gap-2"><Button onClick={discard}>Cancel</Button><Button kind="primary" onClick={() => save(saveForPage[page]!) }>Save changes</Button></div>}</div>{notice && <p className="mb-5 rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-200">{notice}</p>}<PageEditor page={page} content={content} setSection={setSection} messages={messages} updateMessage={updateMessage} /></div></div></div></Shell>;
};

const PageEditor: React.FC<{ page: Page; content: Content; setSection: (section: string, value: any) => void; messages: Message[]; updateMessage: (id: string, status: Message['status']) => void }> = ({ page, content, setSection, messages, updateMessage }) => {
  const profile = content.profile || {}; const replace = (section: string, index: number, item: any) => setSection(section, (content[section] || []).map((entry: any, i: number) => i === index ? item : entry)); const remove = (section: string, index: number) => setSection(section, (content[section] || []).filter((_: any, i: number) => i !== index)); const add = (section: string, item: any) => setSection(section, [...(content[section] || []), item]);
  if (page === 'dashboard') return <div className="grid gap-5 md:grid-cols-3"><Card title="Content overview" description="Your public portfolio is unchanged; these forms update its data."><p className="text-3xl font-bold text-blue-400">{content.projects?.length || 0}</p><p className="text-sm text-slate-400">Projects</p></Card><Card title="Credentials"><p className="text-3xl font-bold text-purple-400">{content.certifications?.length || 0}</p><p className="text-sm text-slate-400">Certificates</p></Card><Card title="Inbox"><p className="text-3xl font-bold text-emerald-400">{messages.filter((m) => m.status === 'new').length}</p><p className="text-sm text-slate-400">New messages</p></Card><div className="md:col-span-3"><Card title="Quick start" description="Choose a page in the sidebar, edit its fields, then save. Media uploads are sent directly to the existing Cloudinary endpoint."><div className="flex flex-wrap gap-2"><span className="rounded bg-slate-800 px-3 py-1.5 text-sm">Profile photo</span><span className="rounded bg-slate-800 px-3 py-1.5 text-sm">Projects</span><span className="rounded bg-slate-800 px-3 py-1.5 text-sm">Certificates</span><span className="rounded bg-slate-800 px-3 py-1.5 text-sm">Resume PDF</span></div></Card></div></div>;
  if (page === 'profile') return <Card title="Profile & hero" description="The current photo is shown below. Select a replacement image directly from your computer."><div className="grid gap-5 md:grid-cols-2"><div className="space-y-4"><Field label="Full name" value={profile.name} onChange={(v) => setSection('profile', { ...profile, name: v })}/><Field label="Short name" value={profile.shortName} onChange={(v) => setSection('profile', { ...profile, shortName: v })}/><Field label="Initials" value={profile.initials} onChange={(v) => setSection('profile', { ...profile, initials: v })}/><Field label="Professional title" value={profile.title} onChange={(v) => setSection('profile', { ...profile, title: v })}/><Area label="Hero tagline" value={profile.tagline} onChange={(v) => setSection('profile', { ...profile, tagline: v })}/><Area label="Typing roles (one per line)" value={(profile.typingWords || []).join('\n')} onChange={(v) => setSection('profile', { ...profile, typingWords: v.split('\n').map((x) => x.trim()).filter(Boolean) })}/></div><div className="rounded-xl border border-slate-800 bg-slate-950 p-5"><p className="mb-3 text-sm font-medium">Profile photo</p><img src={profile.profileImage || chetanHeroImg} alt="Current profile" className="mb-4 aspect-square w-56 rounded-xl object-cover" /><Upload kind="profile" accept="image/jpeg,image/png,image/webp" label="Select new photo" onUploaded={(url) => setSection('profile', { ...profile, profileImage: url })}/></div></div></Card>;
  if (page === 'about') return <Card title="About" description="Edit the introduction and portfolio statistics."><div className="space-y-5">{(profile.aboutIntro || []).map((paragraph: string, index: number) => <div key={index} className="flex gap-3"><div className="flex-1"><Area label={`Paragraph ${index + 1}`} value={paragraph} onChange={(v) => { const aboutIntro = [...profile.aboutIntro]; aboutIntro[index] = v; setSection('profile', { ...profile, aboutIntro }); }}/></div><Button kind="danger" onClick={() => setSection('profile', { ...profile, aboutIntro: profile.aboutIntro.filter((_: string, i: number) => i !== index) })}>Delete</Button></div>)}<Button onClick={() => setSection('profile', { ...profile, aboutIntro: [...(profile.aboutIntro || []), ''] })}>Add paragraph</Button><div className="grid gap-4 md:grid-cols-4"><Field label="Years coding" value={profile.stats?.yearsOfExperience} onChange={(v) => setSection('profile', { ...profile, stats: { ...profile.stats, yearsOfExperience: v } })}/><Field label="Apps built" value={profile.stats?.projectsCompleted} onChange={(v) => setSection('profile', { ...profile, stats: { ...profile.stats, projectsCompleted: v } })}/><Field label="Hackathons" value={profile.stats?.hackathonsParticipated} onChange={(v) => setSection('profile', { ...profile, stats: { ...profile.stats, hackathonsParticipated: v } })}/><Field label="Certificates" value={profile.stats?.certificationsEarned} onChange={(v) => setSection('profile', { ...profile, stats: { ...profile.stats, certificationsEarned: v } })}/></div></div></Card>;
  if (page === 'education') return <Collection title="Education" items={content.education || []} add={() => add('education', { id: crypto.randomUUID(), degree: '', major: '', institution: '', expectedGraduation: '', currentYear: '', status: 'Active Student' })} render={(item, index) => <div className="grid gap-4 md:grid-cols-2"><Field label="Degree" value={item.degree} onChange={(v) => replace('education', index, { ...item, degree: v })}/><Field label="Major" value={item.major} onChange={(v) => replace('education', index, { ...item, major: v })}/><Field label="Institution" value={item.institution} onChange={(v) => replace('education', index, { ...item, institution: v })}/><Field label="Expected graduation" type="date" value={item.expectedGraduation?.length === 4 ? `${item.expectedGraduation}-01-01` : item.expectedGraduation} onChange={(v) => replace('education', index, { ...item, expectedGraduation: v.slice(0, 4) })}/><Field label="Current year" value={item.currentYear} onChange={(v) => replace('education', index, { ...item, currentYear: v })}/><Field label="Status" value={item.status} onChange={(v) => replace('education', index, { ...item, status: v })}/><Button kind="danger" onClick={() => remove('education', index)}>Delete</Button></div>}/>;
  if (page === 'skills') return <Collection title="Skills" items={content.skills || []} add={() => add('skills', { title: 'New category', iconName: 'Code2', skills: [] })} render={(item, index) => <div className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><Field label="Category title" value={item.title} onChange={(v) => replace('skills', index, { ...item, title: v })}/><Field label="Icon name" value={item.iconName} onChange={(v) => replace('skills', index, { ...item, iconName: v })}/></div>{(item.skills || []).map((skill: any, skillIndex: number) => <div key={skillIndex} className="grid gap-3 rounded-lg bg-slate-950 p-3 md:grid-cols-4"><Field label="Skill" value={skill.name} onChange={(v) => { const skills = [...item.skills]; skills[skillIndex] = { ...skill, name: v }; replace('skills', index, { ...item, skills }); }}/><Field label="Level (0-100)" type="number" value={skill.level} onChange={(v) => { const skills = [...item.skills]; skills[skillIndex] = { ...skill, level: Number(v) }; replace('skills', index, { ...item, skills }); }}/><Field label="Badge" value={skill.badge} onChange={(v) => { const skills = [...item.skills]; skills[skillIndex] = { ...skill, badge: v }; replace('skills', index, { ...item, skills }); }}/><Button kind="danger" onClick={() => replace('skills', index, { ...item, skills: item.skills.filter((_: any, i: number) => i !== skillIndex) })}>Delete</Button></div>)}<div className="flex gap-2"><Button onClick={() => replace('skills', index, { ...item, skills: [...item.skills, { name: '', level: 50, badge: '' }] })}>Add skill</Button><Button kind="danger" onClick={() => remove('skills', index)}>Delete category</Button></div></div>}/>;
  if (page === 'projects') return <Collection title="Projects" items={content.projects || []} add={() => add('projects', { id: crypto.randomUUID(), title: '', description: '', longDescription: '', techStack: [], category: 'Full-Stack', githubUrl: '', liveUrl: '', featured: false, highlight: '', image: '' })} render={(item, index) => <ProjectForm item={item} update={(v) => replace('projects', index, v)} remove={() => remove('projects', index)}/>}/>;
  if (page === 'experience') return <Collection title="Experience & internships" items={content.experience || []} add={() => add('experience', { id: crypto.randomUUID(), company: '', role: '', startDate: '', endDate: '', description: '', current: false })} render={(item, index) => <div className="grid gap-4 md:grid-cols-2"><Field label="Company" value={item.company} onChange={(v) => replace('experience', index, { ...item, company: v })}/><Field label="Role" value={item.role} onChange={(v) => replace('experience', index, { ...item, role: v })}/><Field label="Start date" type="date" value={item.startDate} onChange={(v) => replace('experience', index, { ...item, startDate: v })}/><Field label="End date" type="date" value={item.endDate} onChange={(v) => replace('experience', index, { ...item, endDate: v })}/><div className="md:col-span-2"><Area label="Description" value={item.description} onChange={(v) => replace('experience', index, { ...item, description: v })}/></div><Toggle label="Currently working here" checked={!!item.current} onChange={(v) => replace('experience', index, { ...item, current: v })}/><Button kind="danger" onClick={() => remove('experience', index)}>Delete</Button></div>}/>;
  if (page === 'certifications') return <Collection title="Certificates" description="Upload a PDF, JPG, or PNG directly from your computer." items={content.certifications || []} add={() => add('certifications', { id: crypto.randomUUID(), title: '', issuer: '', date: '', icon: 'Award', category: '', assetUrl: '' })} render={(item, index) => <div className="grid gap-4 md:grid-cols-2"><Field label="Title" value={item.title} onChange={(v) => replace('certifications', index, { ...item, title: v })}/><Field label="Issuer" value={item.issuer} onChange={(v) => replace('certifications', index, { ...item, issuer: v })}/><Field label="Issue date" type="date" value={item.date} onChange={(v) => replace('certifications', index, { ...item, date: v })}/><Field label="Category" value={item.category} onChange={(v) => replace('certifications', index, { ...item, category: v })}/><Field label="Icon" value={item.icon} onChange={(v) => replace('certifications', index, { ...item, icon: v })}/><div>{item.assetUrl && (item.assetUrl.includes('.pdf') ? <a className="text-sm text-blue-300 underline" href={item.assetUrl} target="_blank" rel="noreferrer">View uploaded PDF</a> : <img src={item.assetUrl} className="mb-2 h-20 rounded object-cover" />)}<Upload kind="certificates" accept="application/pdf,image/jpeg,image/png" label="Select certificate file" onUploaded={(url) => replace('certifications', index, { ...item, assetUrl: url })}/></div><Button kind="danger" onClick={() => remove('certifications', index)}>Delete</Button></div>}/>;
  if (page === 'achievements') return <Collection title="Achievements" items={content.achievements || []} add={() => add('achievements', { id: crypto.randomUUID(), title: '', event: '', description: '', status: '', badge: '', image: '' })} render={(item, index) => <div className="grid gap-4 md:grid-cols-2"><Field label="Title" value={item.title} onChange={(v) => replace('achievements', index, { ...item, title: v })}/><Field label="Event" value={item.event} onChange={(v) => replace('achievements', index, { ...item, event: v })}/><Field label="Status" value={item.status} onChange={(v) => replace('achievements', index, { ...item, status: v })}/><Field label="Badge" value={item.badge} onChange={(v) => replace('achievements', index, { ...item, badge: v })}/><div className="md:col-span-2"><Area label="Description" value={item.description} onChange={(v) => replace('achievements', index, { ...item, description: v })}/></div><div>{item.image && <img src={item.image} className="mb-2 h-20 rounded object-cover" />}<Upload kind="achievements" accept="image/jpeg,image/png,image/webp" label="Select achievement image" onUploaded={(url) => replace('achievements', index, { ...item, image: url })}/></div><Button kind="danger" onClick={() => remove('achievements', index)}>Delete</Button></div>}/>;
  if (page === 'resume') return <Card title="Resume" description="Select a PDF directly from your computer. There is no URL to paste."><div className="space-y-4"><Field label="File name" value={content.resume?.fileName} onChange={(v) => setSection('resume', { ...content.resume, fileName: v })}/>{content.resume?.url && <a href={content.resume.url} target="_blank" rel="noreferrer" className="block text-sm text-blue-300 underline">View current resume PDF</a>}<Upload kind="resume" accept="application/pdf" label="Select resume PDF" onUploaded={(url) => setSection('resume', { ...content.resume, url })}/></div></Card>;
  if (page === 'social') return <Card title="Social links & contact"><div className="grid gap-4 md:grid-cols-2"><Field label="Email" value={profile.email} onChange={(v) => setSection('profile', { ...profile, email: v })}/><Field label="Location" value={profile.location} onChange={(v) => setSection('profile', { ...profile, location: v })}/><Field label="GitHub URL" value={content.social?.github} onChange={(v) => setSection('social', { ...content.social, github: v })}/><Field label="LinkedIn URL" value={content.social?.linkedin} onChange={(v) => setSection('social', { ...content.social, linkedin: v })}/></div><p className="mt-4 text-xs text-amber-300">Email and location are saved with Profile / Hero. Save that page after editing them.</p></Card>;
  if (page === 'githubSettings') return <Card title="GitHub settings"><div className="grid gap-4 md:grid-cols-3"><Field label="GitHub username" value={content.githubSettings?.username} onChange={(v) => setSection('githubSettings', { ...content.githubSettings, username: v })}/>{['totalRepos', 'totalStars', 'totalCommits2026', 'longestStreak', 'pullRequests', 'issuesSolved'].map((key) => <Field key={key} label={key.replace(/([A-Z])/g, ' $1')} type="number" value={content.githubSettings?.[key]} onChange={(v) => setSection('githubSettings', { ...content.githubSettings, [key]: Number(v) })}/>)}</div></Card>;
  if (page === 'messages') return <Card title="Contact messages" description="Messages are captured alongside the existing Nodemailer delivery.">{messages.length ? <div className="space-y-3">{messages.map((message) => <article key={message._id} className="rounded-lg border border-slate-800 bg-slate-950 p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{message.name}</strong><span className="text-xs text-slate-400">{new Date(message.createdAt).toLocaleString()}</span></div><p className="mt-1 text-sm text-blue-300">{message.email}{message.subject && ` · ${message.subject}`}</p><p className="mt-3 text-sm text-slate-300">{message.message}</p><div className="mt-3 flex items-center gap-2"><select value={message.status} onChange={(e) => updateMessage(message._id, e.target.value as Message['status'])} className="rounded border border-slate-700 bg-slate-900 px-2 py-1 text-xs"><option value="new">New</option><option value="read">Read</option><option value="archived">Archived</option></select></div></article>)}</div> : <p className="text-sm text-slate-400">No messages yet.</p>}</Card>;
  return <Card title="Settings" description="Authentication and integrations are intentionally configured through secure server environment variables."><div className="space-y-3 text-sm text-slate-300"><p>Admin username, bcrypt password hash, JWT secret, MongoDB URI, and Cloudinary credentials stay in <code className="rounded bg-slate-800 px-1.5 py-0.5">backend/.env</code>.</p><p>They are not exposed or editable in the browser.</p></div></Card>;
};

const Collection: React.FC<{ title: string; description?: string; items: any[]; add: () => void; render: (item: any, index: number) => React.ReactNode }> = ({ title, description, items, add, render }) => <Card title={title} description={description}><div className="space-y-4">{items.map((item, index) => <div key={item.id || index} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><p className="mb-4 text-xs font-mono text-slate-500">ITEM {index + 1}</p>{render(item, index)}</div>)}<Button onClick={add}>Add {title.slice(0, -1)}</Button></div></Card>;
const ProjectForm: React.FC<{ item: any; update: (item: any) => void; remove: () => void }> = ({ item, update, remove }) => <div className="grid gap-4 md:grid-cols-2"><Field label="Project title" value={item.title} onChange={(v) => update({ ...item, title: v })}/><label className="block text-sm font-medium text-slate-300">Category<select value={item.category} onChange={(e) => update({ ...item, category: e.target.value })} className="mt-1.5 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm"><option>Full-Stack</option><option>AI & ML</option><option>Hackathon</option></select></label><div className="md:col-span-2"><Area label="Short description" value={item.description} onChange={(v) => update({ ...item, description: v })}/></div><div className="md:col-span-2"><Area label="Long description" value={item.longDescription} onChange={(v) => update({ ...item, longDescription: v })}/></div><Field label="Highlight" value={item.highlight} onChange={(v) => update({ ...item, highlight: v })}/><Field label="Technologies (comma separated)" value={(item.techStack || []).join(', ')} onChange={(v) => update({ ...item, techStack: v.split(',').map((x: string) => x.trim()).filter(Boolean) })}/><Field label="GitHub URL" value={item.githubUrl} onChange={(v) => update({ ...item, githubUrl: v })}/><Field label="Live URL" value={item.liveUrl} onChange={(v) => update({ ...item, liveUrl: v })}/><Toggle label="Featured project" checked={!!item.featured} onChange={(v) => update({ ...item, featured: v })}/><div>{item.image && <img src={item.image} className="mb-2 h-20 rounded object-cover" />}<Upload kind="projects" accept="image/jpeg,image/png,image/webp" label="Select project image" onUploaded={(url) => update({ ...item, image: url })}/></div><Button kind="danger" onClick={remove}>Delete project</Button></div>;

const Login: React.FC<{ onSuccess: () => void }> = ({ onSuccess }) => { const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await request('/api/admin/login', { method: 'POST', body: JSON.stringify({ username, password }) }); onSuccess(); } catch (e) { setError(e instanceof Error ? e.message : 'Login failed.'); } finally { setBusy(false); } }; return <Shell><form onSubmit={submit} className="mx-auto mt-24 max-w-md rounded-2xl border border-slate-800 bg-slate-900/70 p-8 shadow-2xl"><p className="font-mono text-xs text-blue-400">PRIVATE AREA</p><h1 className="mt-2 text-2xl font-bold">Portfolio admin</h1><p className="mt-2 text-sm text-slate-400">Sign in with the server-configured admin account.</p><div className="mt-6 space-y-4"><Field label="Username" value={username} onChange={setUsername}/><Field label="Password" type="password" value={password} onChange={setPassword}/></div>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}<Button type="submit" kind="primary" disabled={busy} >{busy ? 'Signing in…' : 'Sign in'}</Button></form></Shell>; };
